language: node_js

node_js:
  - "lts/*"
  - "node"
  - "8"
  - "7"
  - "6"

# Run lint and tests+coverage in parallel
env:
  - TEST_CMD=lint
  - TEST_CMD=coverage

script: npm run $TEST_CMD

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
