language: node_js

node_js:
  - "lts/*"
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "iojs"

script:
  - npm run lint
  - npm run coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
